[platformio]
default_envs = lolin_s2_mini

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -I${platformio.packages_dir}/framework-arduinoespressif32/libraries/WiFi/src
  -I${platformio.packages_dir}/framework-arduinoespressif32/libraries/WiFiClientSecure/src
lib_deps =
  olikraus/U8g2 @ ^2.35.19
  links2004/WebSockets @ ^2.6.1
  madhephaestus/ESP32Encoder @ ^0.11.7

[env:lolin_s2_mini]
board = lolin_s2_mini
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32dev]
board = esp32dev
build_flags =
  ${env.build_flags}
